# Generated by Django 3.0.4 on 2020-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('sub_grade', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
